### ISSUE TITLE
create .ghuser

### ISSUE THREAD

**Issue by Marco-Pellegrino** [compas-dev/compas-actions.ghpython_components#2]
Hi @gonzalocasas 
I am trying to use this AMAZING feature but there is something that doesn't work in my workflow.

The action seems to be completed with positive result but I am not sure if everythings is correct.
Can you please assist?
Can you maybe create a quick .gif to show me?

I can not find a way to find the file on github at the end of the action

Thanks,
Marco

![image](https://user-images.githubusercontent.com/53620289/140839026-72816e5c-16a8-45f6-bb8e-4e3851836a5e.png)

![image](https://user-images.githubusercontent.com/53620289/140839207-a3e319a8-4f10-4bcf-9c39-cf2789812097.png)

**Comment by gonzalocasas** [comment]
Hi @Marco-Pellegrino ! Ah, yep, I've heard the same thing from others. The action is working correctly, but it might not be clear that, unless you do an extra step with the output files, those are only inside the build but never accessible outside that. I will add an extra example on how to take the built files and create build assets out of them so that they can be retrieved. (What we do in compas.dev is to bundle them immediately into the release, you can check our repo for more details about that if curious).

**Comment by gonzalocasas** [comment]
I added some notes about how to use `upload-artifacts` as one uploading options, and also comments on how this is used from COMPAS to include in the `pip` installable package: https://github.com/compas-dev/compas-actions.ghpython_components#where-are-the-generated-components
